/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.html", "./src/**/*.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#474747",
        "data-blue": "#008cc7",
        "surface-container": "#eceef0",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#b9c7e0",
        "on-primary-fixed": "#1b1b1b",
        "on-background": "#1b1b1b",
        primary: "#000000",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-container": "#1b1b1b",
        "on-surface-variant": "#45464d",
        tertiary: "#000000",
        "on-secondary-container": "#556379",
        "surface-container-low": "#f3f3f3",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#848484",
        "outline-variant": "#cfc4c5",
        "surface-dim": "#dadada",
        "secondary-container": "#d2e1fa",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed": "#1b1b1b",
        background: "#f9f9f9",
        "on-secondary-fixed": "#0d1c2e",
        "inverse-surface": "#303030",
        "secondary-fixed": "#d5e3fc",
        "inverse-on-surface": "#f1f1f1",
        "tertiary-fixed-dim": "#c6c6c6",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#474747",
        "surface-tint": "#5e5e5e",
        "surface-container-high": "#e8e8e8",
        warning: "#a67300",
        surface: "#f9f9f9",
        "primary-fixed-dim": "#c6c6c6",
        "on-surface": "#1b1b1b",
        outline: "#7e7576",
        "inverse-primary": "#c6c6c6",
        "primary-container": "#1b1b1b",
        "primary-fixed": "#e2e2e2",
        "surface-container-highest": "#e2e2e2",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        "surface-variant": "#e2e2e2",
        "on-tertiary-container": "#848484",
        "on-primary": "#ffffff",
        success: "#1a754c",
        "on-secondary-fixed-variant": "#3a485c",
        secondary: "#515f74",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "table-cell-padding": "8px 12px",
        "sidebar-width": "260px",
        gutter: "16px",
        "max-width": "1600px",
        "margin-desktop": "32px",
        unit: "4px",
      },
      fontFamily: {
        "headline-lg": ["Inter Variable", "Inter", "sans-serif"],
        "display-lg": ["Inter Variable", "Inter", "sans-serif"],
        "title-lg": ["Inter Variable", "Inter", "sans-serif"],
        "label-caps": ["Inter Variable", "Inter", "sans-serif"],
        "title-sm": ["Inter Variable", "Inter", "sans-serif"],
        "body-lg": ["Inter Variable", "Inter", "sans-serif"],
        "mono-data": ["JetBrains Mono Variable", "JetBrains Mono", "monospace"],
        "body-sm": ["Inter Variable", "Inter", "sans-serif"],
        "mono-data-sm": ["JetBrains Mono Variable", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["44px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "700" }],
        "title-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "mono-data": ["13px", { lineHeight: "16px", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "mono-data-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
